#!/usr/bin/env bash
set -euo pipefail

source /usr/local/etc/faibuilder.conf

mkdir -p "${MIRROR_DIR}" "${OUTPUT_DIR}"

echo ">> Starting fai-mirror..."
fai-mirror \
	   -b \
           -m1 \
           -c"${CLASSES}" \
           "${MIRROR_DIR}"

echo ">> make nfsroot"
fai-make-nfsroot -v

echo ">> Building ISO with fai-cd..."
fai-cd     \
           -g grub.cfg.install-only \
           -m "${MIRROR_DIR}" \
           "${OUTPUT_DIR}/faicd.iso"

echo ">> Done: your ISO is at ${OUTPUT_DIR}/faicd.iso"
