#!/usr/bin/env bash
set -euo pipefail

source /srv/fai/faibuilder.conf

mkdir -p \
        "${CONFIG_DIR}" \
        "${MIRROR_DIR}" \
        "${NFSROOT_DIR}" \
        "${OUTPUT_DIR}"

chown root:root \
        "${MIRROR_DIR}" \
        "${NFSROOT_DIR}" \
        "${OUTPUT_DIR}"

chmod 0755 \
        "${CONFIG_DIR}" \
        "${MIRROR_DIR}" \
        "${NFSROOT_DIR}" \
        "${OUTPUT_DIR}"

echo "Starting fai-mirror"
echo
[ ! -f "${MIRROR_DIR}/mirror-is-up-to-date" ] && \
        fai-mirror \
           -b \
           -m1 \
           -c"${CLASSES},GRUB_PC,GRUB_EFI,AMD64" \
           "${MIRROR_DIR}"
touch "${MIRROR_DIR}/mirror-is-up-to-date"
echo

echo "Make fai nfsroot"
echo
[ ! -f "/srv/fai/nfsroot/.THIS_IS_THE_FAI_NFSROOT" ] && \
        fai-make-nfsroot \
        -B /srv/fai/${BASE_FILE} \
        -f \
        -v
echo

echo "Building ISO with fai-cd..."
echo
echo "echo ${CLASSES//,/ }" >/srv/fai/config/class/95-fai.me
chmod +x /srv/fai/config/class/95-fai.me
fai-cd     \
           -g /srv/fai/config/grub.cfg.install-only \
           -m "${MIRROR_DIR}" \
           "${OUTPUT_DIR}/faicd.iso"
echo

echo "Done: your ISO is at ${OUTPUT_DIR}/faicd.iso"
echo
