#!/usr/bin/env bash

set -euo pipefail

sudo podman \
	run \
	-it \
	--entrypoint /bin/bash \
	--privileged \
	--rm  \
	--name faibuilder \
	-v ./config:/srv/fai/config:ro,Z \
	-v ./mirror:/srv/fai/mirror:Z \
	-v ./output:/output:Z \
	faibuilder:24.04
