#!/usr/bin/env bash

set -euo pipefail

source ./fai/faibuilder.conf

sudo podman \
	run \
	--privileged \
	--rm  \
	--name faibuilder \
	-v ./fai/faibuilder.conf:/srv/fai/faibuilder.conf:ro,z \
	-v ./fai/${BASE_FILE}:/srv/fai/${BASE_FILE}:ro,z \
	-v ./fai/config:/srv/fai/config:z \
	-v ./fai/mirror:/srv/fai/mirror:z \
	-v ./fai/nfsroot:/srv/fai/nfsroot:z \
	-v ./fai/output:/srv/fai/output:z \
	faibuilder:trixie
