#!/usr/bin/env -S python3 -u
import logging

import os
import sys
import subprocess
import shlex
import shutil

from pathlib import Path

import pwd
import grp

import json

BASEFILESDIRPATH = "/srv/fai/basefiles"
FAICONFIGDIRPATH = "/srv/fai/config"
FAIMIRRORDIRPATH = "/srv/fai/mirror"
FAINFSROOTDIRPATH = "/srv/fai/nfsroot"
OUTPUTDIRPATH = "/srv/fai/output"
HOSTCONF = "/srv/fai/host.json"


def subprocess_run_wrapper(
    cmd: str, dryrun: bool = False, **kwargs
) -> subprocess.CompletedProcess | None:
    if kwargs.get("shell"):
        wcmd = cmd
    else:
        wcmd = shlex.split(cmd)

    if dryrun:
        logging.info(f"[DRYRUN] {cmd}")
        return None

    logging.info(f"[EXECUTING] {cmd}")
    return subprocess.run(wcmd, **kwargs)


def get_path(path):
    return Path(path).expanduser().absolute()


def split_multi_ext(path: Path):
    suffixes = "".join(path.suffixes)
    if suffixes:
        stem = path.name[: -len(suffixes)]
        ext = suffixes.lstrip(".")
    else:
        stem = path.name
        ext = ""
    return stem, ext


def is_readable_file(file: Path) -> bool:
    return file.exists() and file.is_file() and os.access(file, os.R_OK)


def do_faimirror(faiclasses: list, faimirrordir: Path, dryrun: bool = False):
    faimirrormarker = faimirrordir / "mirror-is-up-to-date"

    logging.info("Checking mirror freshness")
    if not faimirrormarker.is_file():
        logging.info(
            f"Mirror is outdated or missing, faimirror marker file {shlex.quote(str(faimirrormarker))} is not a file — running fai-mirror"
        )

        subprocess_run_wrapper(
            cmd=(
                "fai-mirror -b -m1 "
                f"-c '{','.join(faiclasses)},GRUB_PC,GRUB_EFI,AMD64,FAIBUILDER' "
                f"{shlex.quote(str(faimirrordir))}"
            ),
            dryrun=dryrun,
        )

        if not dryrun:
            logging.info(
                f"Mirror finished, touching faimirror marker file: {shlex.quote(str(faimirrormarker))}"
            )
            faimirrormarker.touch()
    else:
        logging.info(
            f"Mirror is up to date, faimirror marker file is existing {shlex.quote(str(faimirrormarker))}"
        )


def do_make_basefile(
    basefilesdir: Path, basefile: Path, faiconfigdir: Path, dryrun: bool = False
):
    basefilefull = basefilesdir / basefile

    logging.info(f"Checking if basefile {shlex.quote(str(basefilefull))} exists")
    if not basefilefull.is_file():
        logging.info(
            f"Basefile {shlex.quote(str(basefilefull))} is outdated or missing - running mk-basefile"
        )

        basefilebase, basefileext = split_multi_ext(basefile)

        subprocess_run_wrapper(
            cmd=(
                f"{shlex.quote(str(faiconfigdir / 'basefiles' / 'mk-basefile'))} -J {shlex.quote(str(basefilebase))}"
            ),
            dryrun=dryrun,
            cwd=basefilesdir,
        )

    else:
        logging.info(f"Basefile {shlex.quote(str(basefilefull))} already exists")


def do_make_fainfsroot(
    fainfsrootdir: Path, basefilesdir: Path, basefile: Path, dryrun: bool = False
):
    fainfsrootmarker = fainfsrootdir / ".THIS_IS_THE_FAI_NFSROOT"

    basefilefull = basefilesdir / basefile

    logging.info("Checking NFSROOT freshness")
    if not fainfsrootmarker.is_file():
        logging.info(
            f"NFSROOT is outdated or missing fainfsroot marker file {shlex.quote(str(fainfsrootmarker))} is not a file — running fai-make-nfsroot"
        )

        hooksdir = Path("/etc/fai/nfsroot-hooks")

        logging.info(f"Creating {shlex.quote(str(hooksdir))}")
        hooksdir.mkdir(parents=True, exist_ok=True)

        src = Path("/usr/local/etc/50-add-btrfs")
        dest = hooksdir / src.name

        logging.info(
            f"Copying {shlex.quote(str(src))} to {shlex.quote(str(dest))} and make it executable"
        )
        shutil.copy2(src, dest)

        # chmod +x
        mode = dest.stat().st_mode
        dest.chmod(mode | 0o111)

        logging.info(
            f"Content of {shlex.quote(str(dest))}:\n{str(dest.read_text(encoding='utf-8'))}"
        )

        subprocess_run_wrapper(
            cmd=(f"fai-make-nfsroot -B {shlex.quote(str(basefilefull))} -N -f -v"),
            dryrun=dryrun,
        )

    else:
        logging.info(
            f"NFSROOT seems to be ready - fainfsroot marker file {shlex.quote(str(fainfsrootmarker))} already exists"
        )


def do_build_iso(
    faiclasses: list,
    hostconf: dict,
    faiconfigdir: Path,
    faimirrordir: Path,
    outputdir: Path,
    dryrun: bool = False,
):

    classesfile = faiconfigdir / "class" / "50-host-classes"

    keymap = str(hostconf["keymap"])
    timezone = str(hostconf["timezone"])
    rootpw = str(hostconf["rootpw"])
    username = str(hostconf["username"])
    userpw = str(hostconf["userpw"])
    diskpath = Path(hostconf["diskpath"])
    rootsizemib = int(hostconf["rootsizemib"])
    outfile = Path(hostconf["outfile"])

    outfilefull = outputdir / outfile

    logging.info(f"Building FAI ISO {shlex.quote(str(outfilefull))}  with faicd")

    logging.info("hostconf:")
    logging.info(f"keymap: {str(keymap)}")
    logging.info(f"timezone: {str(timezone)}")
    logging.info("rootpw: hidden")
    logging.info(f"username: {str(username)}")
    logging.info("userpw: hidden")
    logging.info(f"diskpath: {shlex.quote(str(diskpath))}")
    logging.info(f"rootsizemib: {int(rootsizemib)}")
    logging.info(f"outfile: {shlex.quote(str(outfile))}")

    content = (
        "#!/bin/bash\n"
        "# generated by faibuilder\n"
        f"echo '{' '.join(faiclasses)} FAIBUILDER'\n"
    )
    if dryrun:
        logging.info(
            f"[DRYRUN] Would write to {shlex.quote(str(classesfile))}:\n{content.strip()}"
        )
    else:
        logging.info(f"Writing to {shlex.quote(str(classesfile))}:\n{content.strip()}")
        classesfile.write_text(content)

    logging.info(f"Making {shlex.quote(str(classesfile))} executable")
    classesfilemode = classesfile.stat().st_mode
    classesfile.chmod(classesfilemode | 0o111)

    variablesfile = faiconfigdir / "class" / "FAIBUILDER.var"
    content = (
        "# generated by faibuilder\n"
        f"KEYMAP='{str(keymap)}'\n"
        f"TIMEZONE='{str(timezone)}'\n"
        f"ROOTPW={shlex.quote(str(rootpw))}\n"
        f"username='{str(username)}'\n"
        f"USERPW={shlex.quote(str(userpw))}\n"
        f"DISKPATH={shlex.quote(str(diskpath))}\n"
        f"ROOTSIZEMIB='{int(rootsizemib)}'\n"
    )

    if dryrun:
        logging.info(
            f"[DRYRUN] Would write to {shlex.quote(str(variablesfile))}\n{content.strip()}"
        )
    else:
        logging.info(f"Writing to {shlex.quote(str(variablesfile))}\n{content.strip()}")
        variablesfile.write_text(content)

    # logging.info(f"Making {shlex.quote(str(variablesfile))} executable")
    # variablesfilemode = variablesfile.stat().st_mode
    # variablesfile.chmod(variablesfilemode | 0o111)

    subprocess_run_wrapper(
        cmd=(
            "fai-cd "
            f"-g {shlex.quote(str(faiconfigdir / 'grub.cfg'))} "
            f"-m {shlex.quote(str(faimirrordir))} "
            f"{shlex.quote(str(outfilefull))}"
        ),
        dryrun=dryrun,
    )


def main():
    dryrun = False
    logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")

    basefilesdir = get_path(BASEFILESDIRPATH)
    faiconfigdir = get_path(FAICONFIGDIRPATH)
    faimirrordir = get_path(FAIMIRRORDIRPATH)
    fainfsrootdir = get_path(FAINFSROOTDIRPATH)
    outputdir = get_path(OUTPUTDIRPATH)

    logging.info(f"basefilesdir: {shlex.quote(str(basefilesdir))}")
    logging.info(f"faiconfigdir: {shlex.quote(str(faiconfigdir))}")
    logging.info(f"faimirrordir: {shlex.quote(str(faimirrordir))}")
    logging.info(f"fainfsrootdir: {shlex.quote(str(fainfsrootdir))}")
    logging.info(f"outputdir: {shlex.quote(str(outputdir))}")

    # 0
    root_uid = pwd.getpwnam("root").pw_uid
    root_gid = grp.getgrnam("root").gr_gid

    for d in [basefilesdir, faimirrordir, fainfsrootdir, outputdir]:
        if d.exists():
            os.chown(d, root_uid, root_gid)
            d.chmod(0o755)
        else:
            logging.info(f"[WARN] Directory does not exist: {shlex.quote(str(d))}")

    hostconffile = get_path(HOSTCONF)
    if not is_readable_file(file=hostconffile):
        logging.error(
            f"Config file not found or not readable: {shlex.quote(str(hostconffile))}"
        )
        sys.exit(1)
    logging.info(f"hostconffile: {shlex.quote(str(hostconffile))}")
    hostconf = json.loads(hostconffile.read_text(encoding="utf-8"))
    logging.info(f"hostconf:\n{json.dumps(hostconf, indent=2)}")

    faiclasses = hostconf["faiclasses"]
    basefile = Path(hostconf["basefile"])

    logging.info(f"faiclasses: {faiclasses}")
    logging.info(f"basefile: {shlex.quote(str(basefile))}")

    do_faimirror(faiclasses=faiclasses, faimirrordir=faimirrordir, dryrun=dryrun)
    do_make_basefile(
        basefilesdir=basefilesdir,
        basefile=basefile,
        faiconfigdir=faiconfigdir,
        dryrun=dryrun,
    )
    do_make_fainfsroot(
        fainfsrootdir=fainfsrootdir,
        basefilesdir=basefilesdir,
        basefile=basefile,
        dryrun=dryrun,
    )
    do_build_iso(
        faiclasses=faiclasses,
        hostconf=hostconf,
        faiconfigdir=faiconfigdir,
        faimirrordir=faimirrordir,
        outputdir=outputdir,
        dryrun=dryrun,
    )


if __name__ == "__main__":
    main()
